---
resources:
- name: ironbird
  type: git
  webhook_token: ((webhook_token))
  source:
    ignore_paths: [version, README.md]
    <<: &git_source
      uri: git@github.com:EngineerBetter/ironbird.git
      private_key: |
        ((github_private_key))
      branch: main
- name: version
  type: semver
  source:
    driver: git
    branch: main
    file: version
    depth: 1
    <<: *git_source
- name: release
  type: github-release
  source:
    owner: EngineerBetter
    repository: ironbird
    access_token: ((github_access_token))
- name: concourse-tasks
  type: git
  source:
    uri: https://github.com/EngineerBetter/concourse-tasks.git
    branch: 0.0.27
- name: pcf-ops
  type: docker-image
  icon: docker
  source:
    repository: engineerbetter/pcf-ops
    username: ((dockerhub_user))
    password: ((dockerhub_password))
- name: homebrew-tap
  type: git
  icon: github
  source:
    uri: git@github.com:EngineerBetter/homebrew-tap.git
    branch: master
    private_key: ((github_private_key_homebrew))

jobs:
- name: set-pipeline
  serial: true
  plan:
  - get: ironbird
    trigger: true
  - set_pipeline: self
    file: ironbird/ci/pipeline.yml

- name: test
  serial: true
  plan:
  - get: ironbird
    passed: [set-pipeline]
    trigger: true
  - task: test
    config:
      <<: &task-config
        platform: linux
        image_resource:
          type: registry-image
          source: { repository: engineerbetter/pcf-ops }
        inputs:
        - name: ironbird
      run:
        path: bash
        args:
        - -xeuc
        - |
          go get github.com/onsi/ginkgo/ginkgo
          go get github.com/onsi/gomega

          fly login -t this -c ((concourse_url)) -u ((concourse_username)) -p ((concourse_password))
          fly -t this sync

          cd ironbird/integration
          ginkgo -p -- --target this

- name: release
  serial: true
  plan:
  - get: ironbird
    passed: [test]
    trigger: true
  - task: build
    config:
      <<: *task-config
      outputs:
      - name: built
      run:
        path: bash
        args:
        - -xeuc
        - |
          go get github.com/onsi/ginkgo/ginkgo
          go get github.com/onsi/gomega

          cd ironbird
          GOOS=linux ginkgo build .
          mv ironbird.test ../built/ironbird-linux

          GOOS=darwin ginkgo build .
          mv ironbird.test ../built/ironbird-darwin

          echo ironbird > ../built/name
  - put: version
    params:
      bump: patch
  - put: release
    params:
      name: built/name
      tag: version/version
      globs: [built/ironbird*]

- name: update-homebrew-formula
  serial: true
  plan:
  - in_parallel:
    - get: release
      passed: [release]
      trigger: true
    - get: ironbird
      passed: [release]
    - get: homebrew-tap
    - get: concourse-tasks
    - get: pcf-ops
  - task: update-homebrew-formula
    file: ironbird/ci/update-homebrew-formula.yml
  - task: commit
    file: concourse-tasks/git-commit-if-changed/task.yml
    input_mapping: { input: homebrew-tap }
    output_mapping: { output: homebrew-tap }
    params:
      FILES: ironbird.rb
      GIT_AUTHOR_EMAIL: systems@engineerbetter.com
      GIT_AUTHOR_NAME: "CI"
      GIT_COMMIT_MESSAGE: Update Ironbird version
  - put: homebrew-tap
    params:
      repository: homebrew-tap
