---
resources:
- name: ironbird
  type: git
  webhook_token: ((webhook_token))
  source:
    ignore_paths: [version, README.md]
    <<: &git_source
      uri: git@github.com:EngineerBetter/ironbird.git
      private_key: |
        ((github_private_key))
      branch: main
- name: version
  type: semver
  source:
    driver: git
    branch: main
    file: version
    depth: 1
    <<: *git_source
- name: release
  type: github-release
  source:
    owner: EngineerBetter
    repository: ironbird
    access_token: ((github_access_token))

jobs:
- name: set-pipeline
  serial: true
  plan:
  - get: ironbird
    trigger: true
  - set_pipeline: self
    file: ironbird/ci/pipeline.yml

- name: test
  serial: true
  plan:
  - get: ironbird
    passed: [set-pipeline]
    trigger: true
  - task: test
    config:
      <<: &task-config
        platform: linux
        image_resource:
          type: registry-image
          source: { repository: engineerbetter/pcf-ops }
        inputs:
        - name: ironbird
      run:
        path: bash
        args:
        - -xeuc
        - |
          go get github.com/onsi/ginkgo/ginkgo
          go get github.com/onsi/gomega

          fly login -t eb -c https://ci.engineerbetter.com -u admin -p ((concourse_password))
          fly -t eb sync

          cd ironbird/integration
          ginkgo -p

- name: release
  serial: true
  plan:
  - get: ironbird
    passed: [test]
    trigger: true
  - task: build
    config:
      <<: *task-config
      outputs:
      - name: built
      run:
        path: bash
        args:
        - -xeuc
        - |
          go get github.com/onsi/ginkgo/ginkgo
          go get github.com/onsi/gomega

          cd ironbird
          GOOS=linux ginkgo build .
          mv ironbird.test ../built/ironbird-linux

          GOOS=darwin ginkgo build .
          mv ironbird.test ../built/ironbird-darwin

          echo ironbird > ../built/name
  - put: version
    params:
      bump: patch
  - put: release
    params:
      name: built/name
      tag: version/version
      globs: [built/ironbird*]
